spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: DB_USER
    password: Mw4EK57X
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 8B6250645367570404E635266B5966556A5
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

